#spring boot主配置
spring:
  #环境切换
  profiles:
    #active: dev   #开发环境
      active: prod  #生成环境

  #数据源
  datasource:
      #JDBC配置
      driverClass: com.mysql.cj.jdbc.Driver #数据库驱动类
      user: caidong        #数据库用户名
      password: 19971211..    #数据库用户密码
      jdbcUrl: jdbc:mysql://105.201.210.147:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC  #数据库连接URL
      #c3p0连接池
      type: com.mchange.v2.c3p0.ComboPooledDataSource  #指定自定义连接池类型，不指定则默认使用hikari
      dataSourceName: dataSource
      initialPoolSize: 1    #连接池初始化连接数（初始化时获取三个连接，取值应在minPoolSize与maxPoolSize之间。Default: 3）
      minPoolSize: 1        #连接池最小连接数
      maxPoolSize: 30       #连接池最大连接数
      autoCommitOnClose: false  #连接关闭时默认将所有未提交的操作回滚。如果为true，则未提交设置为待提交而不是回滚。默认未false
      checkoutTimeout: 15000    #当连接池用完时客户端调用getConnection()后等待获取新连接的时间，超时后将抛出SQLException,如设为0则无限期等待。单位毫秒。Default: 0
      maxIdleTime: 60      #（连接的最大空闲时间，超过60秒内未使用则连接被丢弃。若为0则永不丢弃。Default: 0）
      acquireRetryAttempts: 30   #连接池在获取连接失败后允许重试次数，默认30
      numHelperThreads: 3        #（c3p0是异步操作的，缓慢的JDBC操作通过帮助进程完成。扩展这些操作可以有效的提升性能，通过多线程实现多个操作同时被执行。Default: 3）
      testConnectionOnCheckout: false   #（因性能消耗大，所以请只在需要的时候使用它。如果设为true那么在每个connection提交的时候都将校验其有效性。建议使用idleConnectionTestPeriod或automaticTestTable等方法来提升连接测试的性能。Default: false）
      testConnectionOnCheckin: true     #（如果设为true那么在取得连接的同时将校验连接的有效性。Default: false）

  #thymeleaf页面模板
  thymeleaf:
      cache: false                   #取消缓存，避免改了模板还要重启服务器，但不配置也没问题
      prefix: classpath:/templates/  #模板文件视图前缀，默认是classpath:/templates/，可不用配置
      suffix: .html                  #模板文件视图后缀，默认是.html，可不用配置
      check-template-location: true  #检查模板位置，这个可以不配置
      encoding: utf-8                #编码字符集，默认是utf-8，可不用配置
      mode: HTML                     #模板样式，默认是HTML，可不用配置
      servlet:
            content-type: text/html

  #文件上传解析器
  #  servlet:
  #      multipart:
  #          enabled: true
  #          max-file-size: 1MB        #单个文件上传的最大上限
  #          max-request-size: 25MB    #所有文件上传的最大上限


#mybatis配置项
mybatis:
    mapper-locations: classpath:mapper/*.xml  #mapper映射文件
    type-aliases-package: com.cd.blog.entity  #实体类别名
    #mybatis配置
    configuration:
        map-underscore-to-camel-case: true  #开启驼峰命名规则


#pagehelper分页
pagehelper:
    helper-dialect: mysql  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
    reasonable: true       #合法性，即纠错机制，配置reasonable为 true，这时如果 pageNum <= 0 会查询第一页，如果 pageNum > pages 会查询最后一页。
    support-methods-arguments: true
    params: count=countSql

#日志记录
logging:
  config: classpath:log4j2-prod.xml  #引用log4j2日志配置文件
  level:
    com.cd.blog.dao: debug  #mybatis log plugin打印完整sql日志


comment.avatar: /image/avatar.jpg